# Generated by Django 2.0.2 on 2020-05-01 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_auto_20200501_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, unique=True, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
