# Generated by Django 2.0.2 on 2020-05-01 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0005_ordertype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discounttype',
            name='orderType_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderType_id',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='orderType_id',
        ),
        migrations.AddField(
            model_name='discounttype',
            name='order_type',
            field=models.CharField(choices=[('takeAway', 'Take away'), ('dineIn', 'Dine in'), ('homeDelivery', 'Home delivery')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superAdmin', 'Super Admin'), ('manager', 'Manager'), ('deliveryBoy', 'Delivery Boy'), ('waiter', 'Waiter'), ('cashier', 'Cashier')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('takeAway', 'Take away'), ('dineIn', 'Dine in'), ('homeDelivery', 'Home delivery')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='order_type',
            field=models.CharField(choices=[('takeAway', 'Take away'), ('dineIn', 'Dine in'), ('homeDelivery', 'Home delivery')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderType',
        ),
    ]
