# Generated by Django 2.0.2 on 2020-05-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0006_auto_20200501_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resturant.Menu'),
            preserve_default=False,
        ),
    ]
